### ISSUE TITLE
Weather info in CZ

### ISSUE THREAD

**Issue by ingbrzy** [BurgerZ/WeatherBZ#25]
Hi... 

Dont know why, but in SLOVAK is also translated weather condition like "mostly cloudy", "evercast", etc... 

but in CZECH its still in English even its translated in the values-cs/strings.xml...

both strings.xml are the same for CZ and SK... (just translated)

Do you have any idea..?

**Comment by BurgerZ** [comment]
"mostly cloudy", "evercast", etc... are not in strings. I'll take a look at wunderground's lang support and change lang codes in app. I'll send a test apk to you soon.
Slovak weather is in slovak or in english?
Give me your email. I'll send you apk.

**Comment by ingbrzy** [comment]
Slovak weather is in slovak... 

thanks

ingbrzy@ingbrzy.eu

**Comment by ingbrzy** [comment]
Perfect.. in test version its working well also in CZ lang... 

:) issue can be closed...

**Comment by BurgerZ** [comment]
Good.
You can provide your users with this version untill it will be released in Play Market.
