### ISSUE TITLE
Clock widget weather

### ISSUE THREAD

**Issue by ingbrzy** [BurgerZ/WeatherBZ#26]
Hi.. 

Weather information below default MIUI clock widget is in English even in Weather BZ its in Slovak.. 
![Screenshot_2013-04-04-06-05-28](https://f.cloud.github.com/assets/1762519/337523/1ad767ec-9cde-11e2-8b7d-808943b62fb5.png)

**Comment by BurgerZ** [comment]
That is the MIUI CP problem, not mine. I will make some changes in my content provider and so you could edit all widgets/lockscreens to use my CP instead of MIUI's one.
