### ISSUE TITLE
If you permit me the upload, German update is done

### ISSUE THREAD

**Issue by ghost** [BurgerZ/WeatherBZ#36]
Doing German for MIUI as well (just since a few days though). GitHub ID, ThaMcBride

**Comment by BurgerZ** [comment]
Add your translation. You are collaborator now.

**Comment by ingbrzy** [comment]
Add me also as collaborator... :) CZECH and SLOVAK lang.. thanks...

**Comment by BurgerZ** [comment]
ingbrzy, Done!

**Comment by Acid-miuipolskapl** [comment]
Hi can you add me as well? I'm MIUI Polish translator :)

**Comment by BurgerZ** [comment]
Acid-miuipolskapl, you are collaborator now too.

**Comment by ghost** [comment]
It's up, including the v4.5.9 changes. Enjoy :)

Mit freundlichen Grüßen
With best regards

Peter McBride

 Date: Tue, 30 Apr 2013 08:44:48 -0700
