### ISSUE TITLE
Usage of \u2011

### ISSUE THREAD

**Issue by ghost** [BurgerZ/WeatherBZ#38]
Have been using \u2011 in the last cosmetics of German. Maybe you can check and confirm the correct usage in your App before letting it out into the wild.

**Comment by BurgerZ** [comment]
I think no need in \u2011, as no need in - sign in that strings)

**Comment by ghost** [comment]
Non-breakable hyphen that is and necessary there in German

Mit freundlichen Grüßen

Peter McBride

Sent from smartphone, therefore quick and dirty.

Andrei Zhukowski notifications@github.com schrieb:

I think no need in \u2011, as no need in - sign in that strings)

---
