### ISSUE TITLE
Adding UV index in Content Provider?

### ISSUE THREAD

**Issue by slyfoxfr** [BurgerZ/WeatherBZ#44]
I propose to add UV index in pro.burgerz.weather/weather ContentProvider (and why not in the application's displayed information?)
Indeed I saw that the variable is available in Wunderground API: http://www.wunderground.com/weather/api/d/docs
Thanks for all your work!

**Comment by BurgerZ** [comment]
I think that is possible.

**Comment by slyfoxfr** [comment]
Thanks.
Do you forecast to do that later?
Can I help in doing so?

**Comment by BurgerZ** [comment]
Thanks, I don't need any help with doing that way. If you want, I could add it tommorrow. ;-)

**Comment by slyfoxfr** [comment]
Thanks a lot! I am developping a MIUI clock and lockscreen widget and I would be very happy to add UV information for users

**Comment by slyfoxfr** [comment]
Thanks a lot: the last version now includes uv index in contentprovider!
