### ISSUE TITLE
clock doesn't update

### ISSUE THREAD

**Issue by vauss** [BurgerZ/WeatherBZ#45]
Since I started using weatherbz I have the problem that the clock widgets not updated correctly and I must click on refresh to update the clock

screenshoots: https://www.dropbox.com/sh/dtibmab1lljy6xu/lQ27zIosHP
device: note2 (stock 4.1.2 & root)
launcher: nova prime

Thanks for your work!

**Comment by gunine** [comment]
Same issue here, the time was not updated correctly sometimes.
Device: Galaxy S3 (Stock 4.1.2 & ROOT)
Launcher: MiHOME

Thanks~

**Comment by BurgerZ** [comment]
That's because of task managers. Try to add weather app to exlusions list of TM (keep in memory option) until I'll rewrite all widgets another way.

**Comment by vauss** [comment]
I'm not using any task manager, maybe samsung task manager is killing the widget but i can't exclude weather bz (no options available)

**Comment by BurgerZ** [comment]
MIUI's v5 task manager killes apps hardly (dirty) - but it has an option to add your aplication to exclusions.
I'll handle this issue.

**Comment by vauss** [comment]
thanks but I'm on stock samsung rom (android 4.1.2). I will wait your fix
