### ISSUE TITLE
Adding local time information in ContentProvider?

### ISSUE THREAD

**Issue by slyfoxfr** [BurgerZ/WeatherBZ#46]
Hi,
After the UV index, another interesting information would be the current local time of a given city in provider "content://pro.burgerz.weather/cities". This would allow to display night/day weather icons in miui widgets.
Thanks a lot for this beautiful and useful software

**Comment by slyfoxfr** [comment]
Sorry for writing again without waiting for an answer but do you think it would be feasible? The availability of the current local time of a given city (this information is delivered by all providers: Faureca, Weather Underground and Accuweather) in provider "content://pro.burgerz.weather/cities" would be very useful.
Thanks

**Comment by BurgerZ** [comment]
content://pro.burgerz.weather/cities has no time information (and it will never had that).
Why do you need time in cities database table?

**Comment by slyfoxfr** [comment]
I need local time for a given city in order to know if I have to display night or day icon (for instance a sun icon or stars icon) in my MIUI widgets. Actually, my widgets change the current city when the user press a widget button (looping on weatherbz configured cities) and display the weather for that city.

**Comment by slyfoxfr** [comment]
Would it be possible to have this information in content://pro.burgerz.weather/weather ?
Thanks

**Comment by BurgerZ** [comment]
Hey, man, have you look at my database. I HAVE sunrizeHour, surizeMinute, sunsetHour andSunsetMinute columns for all cities))

**Comment by slyfoxfr** [comment]
Yes I saw that but let me explain further:
Imagine I am in Paris and I have 2 configured cities: Paris (GMT+1) and New-York (GMT-5).
Today for instance, in the database, Sunset/Sunrize time for paris are: 5:58/21:53 and Sunset/Sunrize time for new-york are: 5:34/20:28 (so twice are expressed in the time zone where the phone is located).
When it is 22:00 in Paris for example (night), there is no mean to know that it is 16:00 in New-York (day) using any database columns.
It would be OK if it were possible to derive the jetlag between the time zone where the phone is located and the considered city :)
But the database does not contain any item with time information related to the time zone of a given city

**Comment by BurgerZ** [comment]
No! Sunset/Sunrize times are expressed in the time zone of the city, not local TZ.
The only thing I can add to database is value "isDayTime"

**Comment by slyfoxfr** [comment]
You are right, sorry. I meant the contrary :)
Using the current local time, It would be possible to know if Sunset time is passed (to display night icon) for a given city if Sunset/sunrize time information were expressed in the local TZ but right now I think it is not possible

**Comment by slyfoxfr** [comment]
The value isDayTime would be perfect !!

**Comment by slyfoxfr** [comment]
Hi,
Finally would it be possible to add the value "isDayTime" to the database?
I thank you very very much in advance.
