### ISSUE TITLE
item "humidity" in "content://pro.burgerz.weather/weather" always contains 0 (with accuweather)

### ISSUE THREAD

**Issue by slyfoxfr** [BurgerZ/WeatherBZ#48]
A little problem: when using accuweather provider, item "humidity" in "content://pro.burgerz.weather/weather" always contains 0.
Thanks

**Comment by BurgerZ** [comment]
accuweather has no pressure and humidity.

**Comment by slyfoxfr** [comment]
I think accuweather does have pressure and humidity: look here: http://api.accuweather.com/developers/currentConditionsAPIParameters

**Comment by BurgerZ** [comment]
I think api I'am using right now does not support pressure and humidity!

**Comment by slyfoxfr** [comment]
Ok thanks a lot. Do you think this API may evolve in the future or no way?

**Comment by BurgerZ** [comment]
I will add new api soon. There will be much more info ;-)

**Comment by slyfoxfr** [comment]
Coool :)
Thanks so much !!
