### ISSUE TITLE
Ukrainian, weather description 

### ISSUE THREAD

**Issue by Anian-igor** [BurgerZ/WeatherBZ#63]
Weather channel - Foreca
If language is Russian weather description in Russian . But weather description in English than I choose Ukrainian.

**Comment by iggyrom** [comment]
Version?

**Comment by Anian-igor** [comment]
4.8.4

**Comment by iggyrom** [comment]
use 4.9.9 beta21

**Comment by Anian-igor** [comment]
Thanks. Success
