### ISSUE TITLE
Weatherprovider.apk changed in 3.11.29

### ISSUE THREAD

**Issue by ingbrzy** [BurgerZ/WeatherBZ#67]
Hi..

In MIUIv5 3.11.29 Xiaomi introduced international support for MIUI Weather... 
They changed also weatherprovider.apk and now, in the system is not working WeatherBZ as main weather app... for showing weather info below clock or alarm... 

As you may know, MIUI Weather is still peace of shit and not working with other locales as EN, CN, TW.... 

Can you fix it in your app please..? to make a support as before... or we have to just replace weatherprovider.apk by old one..?

Thank you...

**Comment by BurgerZ** [comment]
Hi. Yes, I know about provider changes. Not only weather provider has changed, also part of it's data moved to weather app database. That's crap. But I'll try to fix it as soon as possible. Also I can force weather app (native) to use EN locale for searching cities by Mi-Tools functionality.

**Comment by ingbrzy** [comment]
it will be great... but your weather app is still better than miui... :) thanks for the great job..!

**Comment by BurgerZ** [comment]
Beta 23 for tests http://sderni.ru/207672
Changes:
1. Added timeout for locating (10 seconds)
2. Fixed crash (FC) when no location providers enabled in ROM
3. Changed main icons to simple white (need colorize icons option to be turned on in common settings)
4. Updated animations (added night clear and night cloudy), but need to rework night condition defining
5. Fixes, fixes, fixes......... (MIUI support temporary turned off)
